### ISSUE TITLE
Upgrade Rust Version

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hacspec-v2#130] opened 2023-06-08 07:11 UTC
- [ ] Update to the most recent Rust nightly
- [ ] Set recurring task to do this every 3 months

**Comment by W95Psp** [comment] 2023-06-08 07:27
Isn't that a duplicate of #19?

**Comment by franziskuskiefer** [comment] 2023-06-08 07:51
If that's what's supposed to happen there? The title says something else. In any case we are on a 6+ month old version now and have to update. Feel free to close this and change #19.

**Closed** 2023-06-08 07:59 UTC
Labels: frontend
